require "user.plugins"
require "user.core.options"
require "user.core.keymaps"
require "user.core.colorscheme"
require "user.plugins.comment"
require 'user.plugins.lualine'
require "user.plugins.nvim-tree"
require 'user.plugins.nvim-cmp'
require "user.plugins.lsp.mason"
require 'user.plugins.lsp.lspconfig'
require "user.plugins.lsp.lspsaga"
require 'user.plugins.treesitter'
require 'user.plugins.bufferline'
require 'user.plugins.telescope'
require 'user.plugins.gitsigns'
